### ISSUE TITLE
UI Decor

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#1]
### Summary
Currently, the leadership page is just a series of tiles that represent each officer on the homepage. We'd like to make this look a little bit nicer by adding some elements to the website to give it a more complete appearance.

### Task List
 - [x] Add navbar
 - [x] Add header
 - [x] Add footer & some padding at the bottom
 - [x] Tidy up tiles so that they look more uniform
 - [x] Add a search bar in the navbar
 - [x] Add [dark mode](https://javascript.plainenglish.io/how-to-create-light-and-dark-mode-toggle-in-next-js-with-tailwind-61e67518fd2d)
 - [ ] #7

### Additional Context
Most of these changes are for aesthetic purposes, we want our leadership site to look really nice.

**Comment by NickBurnett** [comment]
What would be on the navbar other than the search bar?

**Comment by harshasrikara** [comment]
@NickBurnett See the list of bullet points (the last one)
