### ISSUE TITLE
Add an all accolades page on the website

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#12]
### Summary
We'd like to have a page on the leadership website similar to the shoutouts channel where it displays a list of all the accolades that are being sent from one officer to another.

### Task List
 - [ ] Use [Collection Group Queries](https://firebase.google.com/docs/firestore/query-data/queries) instead of creating a new collection to store all the accolades. 
 - [ ] ~~Create new collection called `accolades`~~
 - [ ] ~~When a new accolade is given add the accolade to this collection as a document. Can use the same schema as the `/officer/<document-id>/accolade/<accolade-id>` documents~~
 - [ ] Create a new document in the `total` collection that will store a fixed (maybe ~25) of the most recent accolades sent out
 - [ ] Use this document to immediately populate the list of accolades displayed on the page

##### Optional
 - [ ] Add an API endpoint to fetch more accolades. Can be with a query parameter like `/api/accolade?n=50`
 - [ ] As user scrolls on the website load up more accolades. Look into more efficient ways to display more accolades with minimal reads. Perhaps create documents with ~25 accolade chunks to load up at once

### Additional Context
Feature requested by @preston-Glenn
