### ISSUE TITLE
Loading indicator between page navigation

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#14]
**Describe new addition**
Need to display a loading spinner / indicator when navigating between different pages. Currently because we use `getServerSideProps` there's a slight 2-3 second delay when going from the home page to a profile page. This can make a user feel like the site momentarily froze since there's no indication that the page is still loading data.

**Task List**
 - [x] Create loading bar / progress spinner icon
 - [x] Set router change events to trigger the loading icon to appear (helpful articles / stack overflow linked below)
 - [x] Optional: Preferably use the `nprogress` package because it looks cool

**Additional context**
 - https://stackoverflow.com/questions/60755316/nextjs-getserversideprops-show-loading
 - https://dev.to/vvo/show-a-top-progress-bar-on-fetch-and-router-events-in-next-js-4df3
