### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#15]
**Describe the issue**
Add documentation to the site for future maintainers

**Task List**
 - [ ] Add information on how the project is structured
 - [x] Add information on how to run the various parts of the project and get setup locally
 - [ ] Add information on how the data is structured
 - [ ] Describe how data is fetched / populated
 - [x] Describe how data was created / parsed / created
 - [ ] Add information on how to make updates when new officers join the organization / old officers graduate

**Additional Context**
Look for next officer to take on official **ACM Historian** role in the organization
