### ISSUE TITLE
[Feature] Anniversary notifications

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#18]
**Describe new addition**
Post slack & email notifications when an anniversary happens for a specific occasion like joining the team, switching divisions, etc.

**Task List**
 - [ ] Create recurring firebase function to check for any anniversaries, run once per day (query for documents where start date == current date -1 year, -2 years and so on)
 - [ ] Add random set of messages to congratulate officers for reaching anniversary dates
 - [ ] Post messages to `#general` on the acmutd slack workspace. See [Birthday Bot](https://github.com/acmutd/calendar-converter) code for the channel url.

**Additional context**
Explore opportunities to send anniversary messages for other events like switching divisions, joining committees, etc. Dates for these events can be found in the `officer/<officer-id>/roles/<role-id>` documents.
