### ISSUE TITLE
Add linkedin link to individual profile pages

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#2]
### Summary
The underlying dataset now has everyone's linkedin profile urls. This information can now be rendered on the UI.

### Task List
 - [x] Fetch LinkedIn url from the backend when reading the rest of the data. The field is called `linkedin` in the dataset.
 - [x] Display linkedin icon on the profile and link to their profile page
 - [x] Error handling / validation checks since there's a few officers that don't have linkedin (either the field itself won't be present in the dataset or for some officers it'll be an empty string)

### Additional Context
Make it look nice.
