### ISSUE TITLE
Update with new information

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#3]
### Summary
Plenty of new officers have joined ACM, update with their information. Note: This issue doesn't require any code changes, just adding into the db.

### Task List
 - [x] New Dev officers
 - [x] New Education officers
 - [x] New HackUTD officers

### Additional Context
Make sure to include subdocuments for each role with appropriate start times. Set end time for new officers to be `Sat Jun 19 2021`... the front-end right now just assumes that if that's the end-date then it'll display their tenure as `Start-date to Present` instead of `Start-date to End-date`.

**Comment by harshasrikara** [comment]
Updated in firestore ✅
