### ISSUE TITLE
[Feature] Link officer pages to participant pages and other way as well

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#49]
**Describe new addition**
If the same person is listed on both the officer page & the membership page then add a way to navigate between them.

**Task List**
 - [ ] Write script/tool to check both collections for overlapping names. If matches are found then create an object in each officer & participant documents as follows

```ts
{
     id: string,
     name: string,
}
```
 - [ ] Update interfaces in the frontend to reflect new field
 - [ ] Update UI to include an optional link to navigate to their respective membership/officer page
 - [ ] Update [documentation](https://docs.leadership.acmutd.co) with the new schema
 - [ ] Update GraphQL API to support this new field (Note: Should be able to query for full officer / participant schema)

**Additional context**
Although it might seem like a good idea to only include the `id` from the other collection, this format of storing the name and id in an object ensures consistency across all the collections when storing pointers to other documents. It also simplifies how the GraphQL API can be adapted to perform deep queries since the same technique is used in multiple places.
