### ISSUE TITLE
Bind Google Workspace Accounts to Tiles

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/leadership#5]
### Summary
Currently the application now supports login via G Suite. This allows for a wide range of features to be added to the leadership site. The first of those being a privacy filter has been added to ensure that only signed in `@acmutd.co` accounts can access the details about other officers within the organization. The next step towards adding customization is to bind Google Workspace accounts with the individual tiles displayed. This would allow officers to customize their pages & sync their information & allow actions to be performed on the site linked to a specific user.

### Task List
 - [ ] If a user after having signed in has not binded their account display an option on the home page that prompts them to do so
 - [ ] Customize home page with information about signed in user (image in nav bar + welcome back `@user` message)
 - [ ] Allow user to select tile to bind their account to (or perform it automatically if possible based on their email  / name)
 - [ ] Save their binded information in firestore
 - [ ] Be able to read back their information when opening up the page (make sure this happens on the server side)

### Additional Context
How "binding" an account to a profile should happen is very open ended. Can be accomplished in a variety of different ways.
